root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["echo 'hello air' > pre_cmd.txt"]
cmd = "go build -o ./tmp/main ./cmd/main.go"
post_cmd = ["echo 'hello air' > post_cmd.txt"]
bin = "./tmp/main"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500 # ms
delay = 0 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms
rerun = false
rerun_delay = 500
args_bin = ["hello", "world"]